/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'

const SettingsLazyRouteImport = createFileRoute('/settings')()
const IncomeLazyRouteImport = createFileRoute('/income')()
const ExpensesLazyRouteImport = createFileRoute('/expenses')()
const DebtsLazyRouteImport = createFileRoute('/debts')()
const CategoriesLazyRouteImport = createFileRoute('/categories')()
const BudgetLazyRouteImport = createFileRoute('/budget')()
const AccountsLazyRouteImport = createFileRoute('/accounts')()
const IndexLazyRouteImport = createFileRoute('/')()

const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const IncomeLazyRoute = IncomeLazyRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/income.lazy').then((d) => d.Route))
const ExpensesLazyRoute = ExpensesLazyRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/expenses.lazy').then((d) => d.Route))
const DebtsLazyRoute = DebtsLazyRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/debts.lazy').then((d) => d.Route))
const CategoriesLazyRoute = CategoriesLazyRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/categories.lazy').then((d) => d.Route))
const BudgetLazyRoute = BudgetLazyRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/budget.lazy').then((d) => d.Route))
const AccountsLazyRoute = AccountsLazyRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/accounts.lazy').then((d) => d.Route))
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AccountsLazyRoute
  '/budget': typeof BudgetLazyRoute
  '/categories': typeof CategoriesLazyRoute
  '/debts': typeof DebtsLazyRoute
  '/expenses': typeof ExpensesLazyRoute
  '/income': typeof IncomeLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AccountsLazyRoute
  '/budget': typeof BudgetLazyRoute
  '/categories': typeof CategoriesLazyRoute
  '/debts': typeof DebtsLazyRoute
  '/expenses': typeof ExpensesLazyRoute
  '/income': typeof IncomeLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/terms': typeof TermsRoute
  '/accounts': typeof AccountsLazyRoute
  '/budget': typeof BudgetLazyRoute
  '/categories': typeof CategoriesLazyRoute
  '/debts': typeof DebtsLazyRoute
  '/expenses': typeof ExpensesLazyRoute
  '/income': typeof IncomeLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms'
    | '/accounts'
    | '/budget'
    | '/categories'
    | '/debts'
    | '/expenses'
    | '/income'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/accounts'
    | '/budget'
    | '/categories'
    | '/debts'
    | '/expenses'
    | '/income'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/terms'
    | '/accounts'
    | '/budget'
    | '/categories'
    | '/debts'
    | '/expenses'
    | '/income'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  TermsRoute: typeof TermsRoute
  AccountsLazyRoute: typeof AccountsLazyRoute
  BudgetLazyRoute: typeof BudgetLazyRoute
  CategoriesLazyRoute: typeof CategoriesLazyRoute
  DebtsLazyRoute: typeof DebtsLazyRoute
  ExpensesLazyRoute: typeof ExpensesLazyRoute
  IncomeLazyRoute: typeof IncomeLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income': {
      id: '/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof IncomeLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  TermsRoute: TermsRoute,
  AccountsLazyRoute: AccountsLazyRoute,
  BudgetLazyRoute: BudgetLazyRoute,
  CategoriesLazyRoute: CategoriesLazyRoute,
  DebtsLazyRoute: DebtsLazyRoute,
  ExpensesLazyRoute: ExpensesLazyRoute,
  IncomeLazyRoute: IncomeLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
