name: 'Test'
on: 
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    container:
      image: node:22
    steps:
    - uses: actions/checkout@v4
    - name: 'Install Node'
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: 'Install Deps'
      run: npm ci
    - name: 'Test'
      run: npx vitest --coverage.enabled true
    - name: 'Report Coverage'
      if: always() 
      uses:  davelosert/vitest-coverage-report-action@v2
    - name: 'Build'
      run: npm run build
    


    
